apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "lakekeeper-operator.fullname" . }}-manager-role
  labels:
  {{- include "lakekeeper-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.lakekeeper.io
  resources:
  - lakekeepers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.lakekeeper.io
  resources:
  - lakekeepers/finalizers
  verbs:
  - update
- apiGroups:
  - cache.lakekeeper.io
  resources:
  - lakekeepers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cache.lakekeeper.io
  resources:
  - projects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.lakekeeper.io
  resources:
  - projects/finalizers
  verbs:
  - update
- apiGroups:
  - cache.lakekeeper.io
  resources:
  - projects/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cache.lakekeeper.io
  resources:
  - warehouses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.lakekeeper.io
  resources:
  - warehouses/finalizers
  verbs:
  - update
- apiGroups:
  - cache.lakekeeper.io
  resources:
  - warehouses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "lakekeeper-operator.fullname" . }}-manager-rolebinding
  labels:
  {{- include "lakekeeper-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "lakekeeper-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "lakekeeper-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'