apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "lakekeeper-operator.fullname" . }}-warehouse-editor-role
  labels:
  {{- include "lakekeeper-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - cache.lakekeeper.io
  resources:
  - warehouses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.lakekeeper.io
  resources:
  - warehouses/status
  verbs:
  - get