---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.lakekeeper.io
  resources:
  - lakekeepers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.lakekeeper.io
  resources:
  - lakekeepers/finalizers
  verbs:
  - update
- apiGroups:
  - cache.lakekeeper.io
  resources:
  - lakekeepers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cache.lakekeeper.io
  resources:
  - projects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.lakekeeper.io
  resources:
  - projects/finalizers
  verbs:
  - update
- apiGroups:
  - cache.lakekeeper.io
  resources:
  - projects/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cache.lakekeeper.io
  resources:
  - warehouses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.lakekeeper.io
  resources:
  - warehouses/finalizers
  verbs:
  - update
- apiGroups:
  - cache.lakekeeper.io
  resources:
  - warehouses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
